name: prelude_flutter_sdk
description: "Prelude Flutter SDK. Easily integrate Prelude in your Flutter application."
version: 0.1.0
homepage: "https://prelude.so"
documentation: "https://docs.prelude.so/introduction/frontend-sdks/flutter"
repository: "https://github.com/prelude-so/flutter-sdk"

topics:
  - otp
  - sms
  - sms-api
  - authentication
  - two-factor-authentication

platforms:
  android:
  ios:

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: so.prelude.fluttersdk
        pluginClass: PreludeFlutterSdkPlugin
      ios:
        pluginClass: PreludeFlutterSdkPlugin
