name: Publish to pub.dev (manual tag)
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish (e.g. v1.0.0)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for OIDC authentication with pub.dev
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.event.inputs.tag }}
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: stable
      - run: flutter pub publish --dry-run
      - run: flutter pub publish --force
